# Generated by Django 4.1.5 on 2023-01-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversieID', models.IntegerField(default=0)),
                ('besteldatum', models.DateTimeField(blank=True, null=True)),
                ('afleverdatum', models.DateTimeField(blank=True, null=True)),
                ('aflevertijd', models.TimeField(blank=True, null=True)),
                ('verzendkosten', models.IntegerField(blank=True, default=0, null=True)),
                ('korting', models.IntegerField(blank=True, default=0, null=True)),
                ('orderprijs', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('totaal', models.IntegerField(blank=True, default=0, null=True)),
                ('aantal', models.IntegerField(blank=True, default=0, null=True)),
                ('product', models.CharField(blank=True, max_length=250, null=True)),
                ('productSKU', models.CharField(blank=True, max_length=250, null=True)),
                ('organisatieID', models.IntegerField(blank=True, default=0, null=True)),
                ('organisatienaam', models.CharField(blank=True, max_length=250, null=True)),
                ('voornaam', models.CharField(blank=True, max_length=250, null=True)),
                ('achternaam', models.CharField(blank=True, max_length=250, null=True)),
                ('tussenvoegsel', models.CharField(blank=True, max_length=250, null=True)),
                ('emailadres', models.CharField(blank=True, max_length=250, null=True)),
                ('telefoonnummer', models.CharField(blank=True, max_length=250, null=True)),
                ('straatnaam', models.CharField(blank=True, max_length=250, null=True)),
                ('huisnummer', models.CharField(blank=True, max_length=250, null=True)),
                ('postcode', models.CharField(blank=True, max_length=250, null=True)),
                ('plaats', models.CharField(blank=True, max_length=250, null=True)),
                ('land', models.CharField(blank=True, max_length=250, null=True)),
                ('postadres_straatnaam', models.CharField(blank=True, max_length=250, null=True)),
                ('postadres_huisnummer', models.CharField(blank=True, max_length=250, null=True)),
                ('postadres_postcode', models.CharField(blank=True, max_length=250, null=True)),
                ('postadres_plaats', models.CharField(blank=True, max_length=250, null=True)),
                ('postadres_land', models.CharField(blank=True, max_length=250, null=True)),
                ('opmerkingen', models.CharField(blank=True, max_length=2500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orderline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(blank=True, max_length=250, null=True)),
                ('productSKU', models.CharField(blank=True, max_length=250, null=True)),
                ('aantal', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversieID', models.IntegerField(default=0)),
                ('besteldatum', models.DateTimeField(blank=True, null=True)),
                ('afleverdatum', models.DateTimeField(blank=True, null=True)),
                ('aflevertijd', models.TimeField(blank=True, null=True)),
                ('verzendkosten', models.IntegerField(blank=True, default=0, null=True)),
                ('korting', models.IntegerField(blank=True, default=0, null=True)),
                ('orderprijs', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('organisatieID', models.IntegerField(blank=True, default=0, null=True)),
                ('organisatienaam', models.CharField(blank=True, max_length=250, null=True)),
                ('voornaam', models.CharField(blank=True, max_length=250, null=True)),
                ('achternaam', models.CharField(blank=True, max_length=250, null=True)),
                ('tussenvoegsel', models.CharField(blank=True, max_length=250, null=True)),
                ('emailadres', models.CharField(blank=True, max_length=250, null=True)),
                ('telefoonnummer', models.CharField(blank=True, max_length=250, null=True)),
                ('straatnaam', models.CharField(blank=True, max_length=250, null=True)),
                ('huisnummer', models.CharField(blank=True, max_length=250, null=True)),
                ('postcode', models.CharField(blank=True, max_length=250, null=True)),
                ('plaats', models.CharField(blank=True, max_length=250, null=True)),
                ('land', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Productinfo',
            fields=[
                ('productID', models.CharField(default='', max_length=5, primary_key=True, serialize=False)),
                ('omschrijving', models.CharField(max_length=250)),
                ('productcode', models.CharField(default='', max_length=3)),
                ('productnaam', models.CharField(max_length=250)),
                ('leverancier', models.CharField(max_length=250)),
                ('verpakkingseenheid', models.IntegerField(default=0)),
                ('gang', models.IntegerField(default=0)),
                ('picknaam', models.CharField(max_length=250)),
                ('pickvolgorde', models.IntegerField(default=0)),
                ('productiekosten', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('verkoop_incl_btw', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('verkoop_excl_btw', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('verpakkingsoort', models.CharField(default='', max_length=15)),
                ('afmeting_lengte_mm', models.IntegerField(default=0)),
                ('afmeting_breedte_mm', models.IntegerField(default=0)),
                ('afmeting_hoogte_mm', models.IntegerField(default=0)),
                ('fust_type', models.CharField(default='', max_length=15)),
                ('aantal_stuks_per_fust', models.IntegerField(default=0)),
                ('verpakkingscombinaties', models.CharField(default='', max_length=10485759)),
            ],
        ),
    ]
