# Generated by Django 4.1.5 on 2023-01-07 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinfo',
            name='aantal_stuks_per_fust',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='fust_type',
        ),
    ]
