# Generated by Django 4.1.5 on 2023-01-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0002_remove_productinfo_aantal_stuks_per_fust_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='productID',
            field=models.CharField(blank=True, default='', max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='productcode',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
    ]
