# Generated by Django 4.1.5 on 2023-01-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0003_alter_productinfo_productid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='productID',
            field=models.CharField(blank=True, default='', max_length=5, primary_key=True, serialize=False, verbose_name='Alleen invullen als je geen automatisch gegenereerd nummer wil'),
        ),
    ]
