# Generated by Django 4.1.5 on 2023-01-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0004_alter_productinfo_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='productID',
            field=models.CharField(blank=True, default='', help_text='Alleen invullen als je geen automatisch gegenereerd nummer wil', max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='productcode',
            field=models.CharField(blank=True, default='', help_text='Alleen invullen als je geen automatisch gegenereerd nummer wil', max_length=3),
        ),
    ]
