# Generated by Django 4.1.5 on 2023-01-07 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0005_alter_productinfo_productid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinfo',
            old_name='verpakkingscombinaties',
            new_name='name',
        ),
    ]
