# Generated by Django 4.1.5 on 2023-01-07 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0006_rename_verpakkingscombinaties_productinfo_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinfo',
            old_name='name',
            new_name='verpakkingscombinatie',
        ),
    ]
