# Generated by Django 4.1.5 on 2023-01-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0008_rename_verpakkingscombinatie_productinfo_combinatie_0_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinfo',
            old_name='combinatie_0',
            new_name='combinatie_1',
        ),
        migrations.RenameField(
            model_name='productinfo',
            old_name='combinatie_25',
            new_name='combinatie_10',
        ),
        migrations.AddField(
            model_name='productinfo',
            name='combinatie_11',
            field=models.CharField(default='', max_length=10485759),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='combinatie_12',
            field=models.CharField(default='', max_length=10485759),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='combinatie_13',
            field=models.CharField(default='', max_length=10485759),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='combinatie_14',
            field=models.CharField(default='', max_length=10485759),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='combinatie_15',
            field=models.CharField(default='', max_length=10485759),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='combinatie_16',
            field=models.CharField(default='', max_length=10485759),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='combinatie_17',
            field=models.CharField(default='', max_length=10485759),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='combinatie_18',
            field=models.CharField(default='', max_length=10485759),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='combinatie_19',
            field=models.CharField(default='', max_length=10485759),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='combinatie_2',
            field=models.CharField(default='', max_length=10485759),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='combinatie_20',
            field=models.CharField(default='', max_length=10485759),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='combinatie_21',
            field=models.CharField(default='', max_length=10485759),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='combinatie_22',
            field=models.CharField(default='', max_length=10485759),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='combinatie_23',
            field=models.CharField(default='', max_length=10485759),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='combinatie_24',
            field=models.CharField(default='', max_length=10485759),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='combinatie_3',
            field=models.CharField(default='', max_length=10485759),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='combinatie_4',
            field=models.CharField(default='', max_length=10485759),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='combinatie_5',
            field=models.CharField(default='', max_length=10485759),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='combinatie_6',
            field=models.CharField(default='', max_length=10485759),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='combinatie_7',
            field=models.CharField(default='', max_length=10485759),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='combinatie_8',
            field=models.CharField(default='', max_length=10485759),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='combinatie_9',
            field=models.CharField(default='', max_length=10485759),
        ),
    ]
