# Generated by Django 4.1.5 on 2023-01-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0009_rename_combinatie_0_productinfo_combinatie_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinfo',
            name='combinatie_1',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='combinatie_10',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='combinatie_11',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='combinatie_12',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='combinatie_13',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='combinatie_14',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='combinatie_15',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='combinatie_16',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='combinatie_17',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='combinatie_18',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='combinatie_19',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='combinatie_2',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='combinatie_20',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='combinatie_21',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='combinatie_22',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='combinatie_23',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='combinatie_24',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='combinatie_3',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='combinatie_4',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='combinatie_5',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='combinatie_6',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='combinatie_7',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='combinatie_8',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='combinatie_9',
        ),
        migrations.AddField(
            model_name='productinfo',
            name='Verpakkingscombinatie_10keer besteld',
            field=models.CharField(default='', help_text='Bijvoorbeeld 4,3,2', max_length=10485759),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='Verpakkingscombinatie_11keer besteld',
            field=models.CharField(default='', help_text='Bijvoorbeeld 4,3,2', max_length=10485759),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='Verpakkingscombinatie_12keer besteld',
            field=models.CharField(default='', help_text='Bijvoorbeeld 4,3,2', max_length=10485759),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='Verpakkingscombinatie_13keer besteld',
            field=models.CharField(default='', help_text='Bijvoorbeeld 4,3,2', max_length=10485759),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='Verpakkingscombinatie_14keer besteld',
            field=models.CharField(default='', help_text='Bijvoorbeeld 4,3,2', max_length=10485759),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='Verpakkingscombinatie_15keer besteld',
            field=models.CharField(default='', help_text='Bijvoorbeeld 4,3,2', max_length=10485759),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='Verpakkingscombinatie_16keer besteld',
            field=models.CharField(default='', help_text='Bijvoorbeeld 4,3,2', max_length=10485759),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='Verpakkingscombinatie_17keer besteld',
            field=models.CharField(default='', help_text='Bijvoorbeeld 4,3,2', max_length=10485759),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='Verpakkingscombinatie_18keer besteld',
            field=models.CharField(default='', help_text='Bijvoorbeeld 4,3,2', max_length=10485759),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='Verpakkingscombinatie_19keer besteld',
            field=models.CharField(default='', help_text='Bijvoorbeeld 4,3,2', max_length=10485759),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='Verpakkingscombinatie_1keer besteld',
            field=models.CharField(default='', help_text='Bijvoorbeeld 4,3,2', max_length=10485759),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='Verpakkingscombinatie_20keer besteld',
            field=models.CharField(default='', help_text='Bijvoorbeeld 4,3,2', max_length=10485759),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='Verpakkingscombinatie_21keer besteld',
            field=models.CharField(default='', help_text='Bijvoorbeeld 4,3,2', max_length=10485759),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='Verpakkingscombinatie_22keer besteld',
            field=models.CharField(default='', help_text='Bijvoorbeeld 4,3,2', max_length=10485759),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='Verpakkingscombinatie_23keer besteld',
            field=models.CharField(default='', help_text='Bijvoorbeeld 4,3,2', max_length=10485759),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='Verpakkingscombinatie_24keer besteld',
            field=models.CharField(default='', help_text='Bijvoorbeeld 4,3,2', max_length=10485759),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='Verpakkingscombinatie_25keer besteld',
            field=models.CharField(default='', help_text='Bijvoorbeeld 4,3,2', max_length=10485759),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='Verpakkingscombinatie_2keer besteld',
            field=models.CharField(default='', help_text='Bijvoorbeeld 4,3,2', max_length=10485759),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='Verpakkingscombinatie_3keer besteld',
            field=models.CharField(default='', help_text='Bijvoorbeeld 4,3,2', max_length=10485759),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='Verpakkingscombinatie_4keer besteld',
            field=models.CharField(default='', help_text='Bijvoorbeeld 4,3,2', max_length=10485759),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='Verpakkingscombinatie_5keer besteld',
            field=models.CharField(default='', help_text='Bijvoorbeeld 4,3,2', max_length=10485759),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='Verpakkingscombinatie_6keer besteld',
            field=models.CharField(default='', help_text='Bijvoorbeeld 4,3,2', max_length=10485759),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='Verpakkingscombinatie_7keer besteld',
            field=models.CharField(default='', help_text='Bijvoorbeeld 4,3,2', max_length=10485759),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='Verpakkingscombinatie_8keer besteld',
            field=models.CharField(default='', help_text='Bijvoorbeeld 4,3,2', max_length=10485759),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='Verpakkingscombinatie_9keer besteld',
            field=models.CharField(default='', help_text='Bijvoorbeeld 4,3,2', max_length=10485759),
        ),
    ]
