# Generated by Django 4.1.5 on 2023-01-07 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0010_remove_productinfo_combinatie_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinfo',
            old_name='Verpakkingscombinatie_10keer besteld',
            new_name='Verpakkingscombinatie_1 keer besteld',
        ),
        migrations.RenameField(
            model_name='productinfo',
            old_name='Verpakkingscombinatie_11keer besteld',
            new_name='Verpakkingscombinatie_10 keer besteld',
        ),
        migrations.RenameField(
            model_name='productinfo',
            old_name='Verpakkingscombinatie_12keer besteld',
            new_name='Verpakkingscombinatie_11 keer besteld',
        ),
        migrations.RenameField(
            model_name='productinfo',
            old_name='Verpakkingscombinatie_13keer besteld',
            new_name='Verpakkingscombinatie_12 keer besteld',
        ),
        migrations.RenameField(
            model_name='productinfo',
            old_name='Verpakkingscombinatie_14keer besteld',
            new_name='Verpakkingscombinatie_13 keer besteld',
        ),
        migrations.RenameField(
            model_name='productinfo',
            old_name='Verpakkingscombinatie_15keer besteld',
            new_name='Verpakkingscombinatie_14 keer besteld',
        ),
        migrations.RenameField(
            model_name='productinfo',
            old_name='Verpakkingscombinatie_16keer besteld',
            new_name='Verpakkingscombinatie_15 keer besteld',
        ),
        migrations.RenameField(
            model_name='productinfo',
            old_name='Verpakkingscombinatie_17keer besteld',
            new_name='Verpakkingscombinatie_16 keer besteld',
        ),
        migrations.RenameField(
            model_name='productinfo',
            old_name='Verpakkingscombinatie_18keer besteld',
            new_name='Verpakkingscombinatie_17 keer besteld',
        ),
        migrations.RenameField(
            model_name='productinfo',
            old_name='Verpakkingscombinatie_19keer besteld',
            new_name='Verpakkingscombinatie_18 keer besteld',
        ),
        migrations.RenameField(
            model_name='productinfo',
            old_name='Verpakkingscombinatie_1keer besteld',
            new_name='Verpakkingscombinatie_19 keer besteld',
        ),
        migrations.RenameField(
            model_name='productinfo',
            old_name='Verpakkingscombinatie_20keer besteld',
            new_name='Verpakkingscombinatie_2 keer besteld',
        ),
        migrations.RenameField(
            model_name='productinfo',
            old_name='Verpakkingscombinatie_21keer besteld',
            new_name='Verpakkingscombinatie_20 keer besteld',
        ),
        migrations.RenameField(
            model_name='productinfo',
            old_name='Verpakkingscombinatie_22keer besteld',
            new_name='Verpakkingscombinatie_21 keer besteld',
        ),
        migrations.RenameField(
            model_name='productinfo',
            old_name='Verpakkingscombinatie_23keer besteld',
            new_name='Verpakkingscombinatie_22 keer besteld',
        ),
        migrations.RenameField(
            model_name='productinfo',
            old_name='Verpakkingscombinatie_24keer besteld',
            new_name='Verpakkingscombinatie_23 keer besteld',
        ),
        migrations.RenameField(
            model_name='productinfo',
            old_name='Verpakkingscombinatie_25keer besteld',
            new_name='Verpakkingscombinatie_24 keer besteld',
        ),
        migrations.RenameField(
            model_name='productinfo',
            old_name='Verpakkingscombinatie_2keer besteld',
            new_name='Verpakkingscombinatie_25 keer besteld',
        ),
        migrations.RenameField(
            model_name='productinfo',
            old_name='Verpakkingscombinatie_3keer besteld',
            new_name='Verpakkingscombinatie_3 keer besteld',
        ),
        migrations.RenameField(
            model_name='productinfo',
            old_name='Verpakkingscombinatie_4keer besteld',
            new_name='Verpakkingscombinatie_4 keer besteld',
        ),
        migrations.RenameField(
            model_name='productinfo',
            old_name='Verpakkingscombinatie_5keer besteld',
            new_name='Verpakkingscombinatie_5 keer besteld',
        ),
        migrations.RenameField(
            model_name='productinfo',
            old_name='Verpakkingscombinatie_6keer besteld',
            new_name='Verpakkingscombinatie_6 keer besteld',
        ),
        migrations.RenameField(
            model_name='productinfo',
            old_name='Verpakkingscombinatie_7keer besteld',
            new_name='Verpakkingscombinatie_7 keer besteld',
        ),
        migrations.RenameField(
            model_name='productinfo',
            old_name='Verpakkingscombinatie_8keer besteld',
            new_name='Verpakkingscombinatie_8 keer besteld',
        ),
        migrations.RenameField(
            model_name='productinfo',
            old_name='Verpakkingscombinatie_9keer besteld',
            new_name='Verpakkingscombinatie_9 keer besteld',
        ),
    ]
