# Generated by Django 4.1.5 on 2023-01-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0011_rename_verpakkingscombinatie_10keer besteld_productinfo_verpakkingscombinatie_1 keer besteld_and_mor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='Verpakkingscombinatie_1 keer besteld',
            field=models.CharField(default='', help_text='Bijvoorbeeld 4,3,2', max_length=300),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='Verpakkingscombinatie_10 keer besteld',
            field=models.CharField(default='', help_text='Bijvoorbeeld 4,3,2', max_length=300),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='Verpakkingscombinatie_11 keer besteld',
            field=models.CharField(default='', help_text='Bijvoorbeeld 4,3,2', max_length=300),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='Verpakkingscombinatie_12 keer besteld',
            field=models.CharField(default='', help_text='Bijvoorbeeld 4,3,2', max_length=300),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='Verpakkingscombinatie_13 keer besteld',
            field=models.CharField(default='', help_text='Bijvoorbeeld 4,3,2', max_length=300),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='Verpakkingscombinatie_14 keer besteld',
            field=models.CharField(default='', help_text='Bijvoorbeeld 4,3,2', max_length=300),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='Verpakkingscombinatie_15 keer besteld',
            field=models.CharField(default='', help_text='Bijvoorbeeld 4,3,2', max_length=300),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='Verpakkingscombinatie_16 keer besteld',
            field=models.CharField(default='', help_text='Bijvoorbeeld 4,3,2', max_length=300),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='Verpakkingscombinatie_17 keer besteld',
            field=models.CharField(default='', help_text='Bijvoorbeeld 4,3,2', max_length=300),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='Verpakkingscombinatie_18 keer besteld',
            field=models.CharField(default='', help_text='Bijvoorbeeld 4,3,2', max_length=300),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='Verpakkingscombinatie_19 keer besteld',
            field=models.CharField(default='', help_text='Bijvoorbeeld 4,3,2', max_length=300),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='Verpakkingscombinatie_2 keer besteld',
            field=models.CharField(default='', help_text='Bijvoorbeeld 4,3,2', max_length=300),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='Verpakkingscombinatie_20 keer besteld',
            field=models.CharField(default='', help_text='Bijvoorbeeld 4,3,2', max_length=300),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='Verpakkingscombinatie_21 keer besteld',
            field=models.CharField(default='', help_text='Bijvoorbeeld 4,3,2', max_length=300),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='Verpakkingscombinatie_22 keer besteld',
            field=models.CharField(default='', help_text='Bijvoorbeeld 4,3,2', max_length=300),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='Verpakkingscombinatie_23 keer besteld',
            field=models.CharField(default='', help_text='Bijvoorbeeld 4,3,2', max_length=300),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='Verpakkingscombinatie_24 keer besteld',
            field=models.CharField(default='', help_text='Bijvoorbeeld 4,3,2', max_length=300),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='Verpakkingscombinatie_25 keer besteld',
            field=models.CharField(default='', help_text='Bijvoorbeeld 4,3,2', max_length=300),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='Verpakkingscombinatie_3 keer besteld',
            field=models.CharField(default='', help_text='Bijvoorbeeld 4,3,2', max_length=300),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='Verpakkingscombinatie_4 keer besteld',
            field=models.CharField(default='', help_text='Bijvoorbeeld 4,3,2', max_length=300),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='Verpakkingscombinatie_5 keer besteld',
            field=models.CharField(default='', help_text='Bijvoorbeeld 4,3,2', max_length=300),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='Verpakkingscombinatie_6 keer besteld',
            field=models.CharField(default='', help_text='Bijvoorbeeld 4,3,2', max_length=300),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='Verpakkingscombinatie_7 keer besteld',
            field=models.CharField(default='', help_text='Bijvoorbeeld 4,3,2', max_length=300),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='Verpakkingscombinatie_8 keer besteld',
            field=models.CharField(default='', help_text='Bijvoorbeeld 4,3,2', max_length=300),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='Verpakkingscombinatie_9 keer besteld',
            field=models.CharField(default='', help_text='Bijvoorbeeld 4,3,2', max_length=300),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='gang',
            field=models.IntegerField(choices=[(1, 'Amuse'), (2, 'Voorgerecht'), (3, 'Soep'), (4, 'Hoofdgerecht'), (5, 'Nagerecht'), (6, 'Bijgerecht'), (7, 'Dranken'), (8, 'Extra'), (9, 'Overig')]),
        ),
    ]
