# Generated by Django 4.1.5 on 2023-01-07 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0012_alter_productinfo_verpakkingscombinatie_1 keer besteld_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gangnummer', models.CharField(default='', max_length=1)),
                ('gangnaam', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Orderextra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productnaam', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Percentuele_kosten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kostennaam', models.CharField(default='', max_length=30)),
                ('kostenomschrijving', models.CharField(default='-', max_length=300)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Variable_kosten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kostennaam', models.CharField(default='', max_length=30)),
                ('kostenomschrijving', models.CharField(default='-', max_length=300)),
                ('kosten_per_eenheid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vermenigvuldiging', models.IntegerField(default=0, help_text='1=Per order, 2=Per hoofdgerecht')),
            ],
        ),
        migrations.CreateModel(
            name='Vaste_kosten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kostennaam', models.CharField(default='', max_length=30)),
                ('kostenomschrijving', models.CharField(default='-', max_length=300)),
                ('kosten', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Productextra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_productnaam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productextra_extra_productnaam', to='hefs.productinfo')),
                ('productnaam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productextra_productnaam', to='hefs.productinfo')),
            ],
        ),
    ]
