# Generated by Django 4.1.5 on 2023-01-08 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0013_gang_orderextra_percentuele_kosten_variable_kosten_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='conversieID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productextra',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='productextra_productnaam', to='hefs.productinfo'),
        ),
        migrations.AlterField(
            model_name='productextra',
            name='extra_productnaam',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='productextra_extra_productnaam', to='hefs.productinfo'),
        ),
        migrations.AlterField(
            model_name='productextra',
            name='productnaam',
            field=models.CharField(blank=True, max_length=250, verbose_name=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='productextra_productnaam', to='hefs.productinfo')),
        ),
    ]
