# Generated by Django 4.1.5 on 2023-01-08 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0014_orderline_conversieid_productextra_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productextra',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hefs.productinfo'),
        ),
        migrations.AlterField(
            model_name='productextra',
            name='productnaam',
            field=models.CharField(blank=True, max_length=250, verbose_name=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hefs.productinfo')),
        ),
    ]
