# Generated by Django 4.1.5 on 2023-01-10 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0015_alter_productextra_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiUrls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='productextra',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='hefs.productinfo'),
        ),
        migrations.AlterField(
            model_name='productextra',
            name='productnaam',
            field=models.CharField(blank=True, max_length=250, verbose_name=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='hefs.productinfo')),
        ),
    ]
