# Generated by Django 4.1.5 on 2023-01-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0018_apiurls_user_id_productextra_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiurls',
            name='begindatum',
            field=models.DateField(null=True),
        ),
    ]
