# Generated by Django 4.1.5 on 2023-01-19 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0019_apiurls_begindatum'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerpakkingsMogelijkheden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=250)),
            ],
        ),
        migrations.RenameModel(
            old_name='Percentuele_kosten',
            new_name='PercentueleKosten',
        ),
        migrations.RenameModel(
            old_name='Variable_kosten',
            new_name='VariableKosten',
        ),
        migrations.RenameModel(
            old_name='Vaste_kosten',
            new_name='VasteKosten',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='conversieID',
        ),
        migrations.RemoveField(
            model_name='productextra',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='Verpakkingscombinatie_1 keer besteld',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='Verpakkingscombinatie_10 keer besteld',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='Verpakkingscombinatie_11 keer besteld',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='Verpakkingscombinatie_12 keer besteld',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='Verpakkingscombinatie_13 keer besteld',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='Verpakkingscombinatie_14 keer besteld',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='Verpakkingscombinatie_15 keer besteld',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='Verpakkingscombinatie_16 keer besteld',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='Verpakkingscombinatie_17 keer besteld',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='Verpakkingscombinatie_18 keer besteld',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='Verpakkingscombinatie_19 keer besteld',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='Verpakkingscombinatie_2 keer besteld',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='Verpakkingscombinatie_20 keer besteld',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='Verpakkingscombinatie_21 keer besteld',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='Verpakkingscombinatie_22 keer besteld',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='Verpakkingscombinatie_23 keer besteld',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='Verpakkingscombinatie_24 keer besteld',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='Verpakkingscombinatie_25 keer besteld',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='Verpakkingscombinatie_3 keer besteld',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='Verpakkingscombinatie_4 keer besteld',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='Verpakkingscombinatie_5 keer besteld',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='Verpakkingscombinatie_6 keer besteld',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='Verpakkingscombinatie_7 keer besteld',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='Verpakkingscombinatie_8 keer besteld',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='Verpakkingscombinatie_9 keer besteld',
        ),
        migrations.AddField(
            model_name='orderline',
            name='order',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='hefs.orders'),
        ),
        migrations.AlterField(
            model_name='productextra',
            name='productnaam',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, related_name='productextra_productnaam', to='hefs.productinfo'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='gang',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, related_name='gang', to='hefs.gang'),
        ),
        migrations.CreateModel(
            name='VerpakkingsCombinaties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bestelde_hoeveelheid', models.FloatField()),
                ('verpakkingscombinatie', models.CharField(max_length=1000)),
                ('verpakkingsmogelijkheid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hefs.verpakkingsmogelijkheden')),
            ],
        ),
        migrations.CreateModel(
            name='PickOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afleverdatum', models.DateTimeField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hefs.orders')),
            ],
        ),
        migrations.CreateModel(
            name='PickItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('omschrijving', models.CharField(max_length=250, null=True)),
                ('hoeveelheid', models.FloatField()),
                ('pick_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hefs.pickorders')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hefs.productinfo')),
            ],
        ),
    ]
