# Generated by Django 4.1.5 on 2023-01-19 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0020_verpakkingsmogelijkheden_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apiurls',
            old_name='url',
            new_name='api',
        ),
    ]
