# Generated by Django 4.1.5 on 2023-01-19 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0022_remove_productinfo_verpakkingseenheid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gangnaam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gangnaam', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='gang',
            name='gangnaam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hefs.gangnaam'),
        ),
    ]
