# Generated by Django 4.1.5 on 2023-01-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0023_gangnaam_alter_gang_gangnaam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gang',
            name='gangnummer',
        ),
        migrations.AlterField(
            model_name='gang',
            name='gangnaam',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='Gangnaam',
        ),
    ]
