# Generated by Django 4.1.5 on 2023-01-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0024_remove_gang_gangnummer_alter_gang_gangnaam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='verpakkingseenheid',
            field=models.IntegerField(default=0),
        ),
    ]
