# Generated by Django 4.1.5 on 2023-01-19 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0025_productinfo_verpakkingseenheid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderextra',
            name='productnaam',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, related_name='orderextra_productnaam', to='hefs.productinfo'),
        ),
    ]
