# Generated by Django 4.1.5 on 2023-01-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0027_remove_pickorders_afleverdatum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='afleverdatum',
            field=models.DateField(blank=True, null=True),
        ),
    ]
