# Generated by Django 4.1.5 on 2023-01-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0028_alter_orders_afleverdatum'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='routenr',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
