# Generated by Django 4.1.5 on 2023-02-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0031_algemeneinformatie'),
    ]

    operations = [
        migrations.AddField(
            model_name='algemeneinformatie',
            name='aantalHoofdgerechten',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='algemeneinformatie',
            name='aantalOrders',
            field=models.IntegerField(default=0),
        ),
    ]
