# Generated by Django 4.1.5 on 2023-07-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0034_verzendopties_neworders_verzendoptie'),
    ]

    operations = [
        migrations.AddField(
            model_name='verzendopties',
            name='verzenddatum',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
