# Generated by Django 4.1.5 on 2023-07-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0035_verzendopties_verzenddatum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verzendopties',
            name='verzenddatum',
            field=models.DateField(blank=True, null=True),
        ),
    ]
