# Generated by Django 4.1.5 on 2023-07-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0036_alter_verzendopties_verzenddatum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailadres', models.CharField(default='', max_length=300, unique=True)),
                ('voornaam', models.CharField(default='', max_length=300)),
                ('tussenvoegsel', models.CharField(default='', max_length=300)),
                ('achternaam', models.CharField(default='', max_length=300)),
                ('postcode', models.CharField(default='', max_length=300)),
                ('plaats', models.CharField(default='', max_length=300)),
                ('ordered_2020', models.BinaryField(blank=True, default=0)),
                ('ordered_2021', models.BinaryField(blank=True, default=0)),
                ('ordered_2022', models.BinaryField(blank=True, default=0)),
                ('ordered_2023', models.BinaryField(blank=True, default=0)),
            ],
        ),
    ]
