# Generated by Django 4.1.5 on 2023-07-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0037_customers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='achternaam',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='plaats',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='postcode',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='tussenvoegsel',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='voornaam',
            field=models.CharField(default='', max_length=300, null=True),
        ),
    ]
