# Generated by Django 4.1.5 on 2023-07-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0038_alter_customers_achternaam_alter_customers_plaats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='ordered_2020',
            field=models.BinaryField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='ordered_2021',
            field=models.BinaryField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='ordered_2022',
            field=models.BinaryField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='ordered_2023',
            field=models.BinaryField(blank=True, default=0, null=True),
        ),
    ]
