# Generated by Django 4.1.5 on 2023-10-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0040_jsondata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='verzendkosten',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
