# Generated by Django 4.1.5 on 2023-10-31 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0043_alter_neworders_verzendkosten'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinfo',
            old_name='productiekosten',
            new_name='inkoop',
        ),
    ]
