# Generated by Django 4.1.5 on 2023-11-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0044_rename_productiekosten_productinfo_inkoop'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='btw_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
