# Generated by Django 4.1.5 on 2023-11-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0046_alter_productinfo_btw_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='btw_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='9% is 1.09', max_digits=6),
        ),
    ]
