# Generated by Django 4.1.5 on 2024-03-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0050_neworders_shopifyid_orders_shopifyid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neworders',
            name='shopifyID',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='shopifyID',
            field=models.BigIntegerField(default=0),
        ),
    ]
