# Generated by Django 4.1.5 on 2024-03-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0051_alter_neworders_shopifyid_alter_orders_shopifyid'),
    ]

    operations = [
        migrations.AddField(
            model_name='algemeneinformatie',
            name='text',
            field=models.CharField(default='', max_length=800),
        ),
    ]
