# Generated by Django 4.1.5 on 2024-04-22 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0052_algemeneinformatie_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Halfproducten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeteenheid', models.CharField(choices=[('KG', 'Kilogram'), ('ST', 'per stuk'), ('LT', 'Liter')], default='KG', max_length=2)),
                ('bereidingswijze', models.CharField(max_length=5000, null=True)),
                ('bereidingskosten', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('product', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='hefs.productinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredienten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeteenheid', models.CharField(choices=[('KG', 'Kilogram'), ('ST', 'per stuk'), ('LT', 'Liter')], default='KG', max_length=2)),
                ('kostenpereenheid', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('halfproduct', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='hefs.halfproducten')),
            ],
        ),
    ]
