# Generated by Django 4.1.5 on 2024-04-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0053_halfproducten_ingredienten'),
    ]

    operations = [
        migrations.AddField(
            model_name='halfproducten',
            name='naam',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='ingredienten',
            name='naam',
            field=models.CharField(default='', max_length=250),
        ),
    ]
