# Generated by Django 4.1.5 on 2024-04-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0054_halfproducten_naam_ingredienten_naam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='halfproducten',
            name='bereidingswijze',
            field=models.TextField(),
        ),
    ]
