# Generated by Django 4.1.5 on 2024-04-22 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0056_alter_halfproducten_bereidingswijze'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredienten',
            name='halfproduct',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='halfproduct_naam', to='hefs.halfproducten'),
        ),
    ]
