# Generated by Django 4.1.5 on 2024-05-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0058_rename_bereidingskosten_halfproducten_bereidingskosten_per_eenheid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredienten',
            name='productinfo',
            field=models.ManyToManyField(related_name='product_ingredienten', to='hefs.productinfo'),
        ),
        migrations.RemoveField(
            model_name='ingredienten',
            name='halfproduct',
        ),
        migrations.AddField(
            model_name='ingredienten',
            name='halfproduct',
            field=models.ManyToManyField(related_name='ingredienten', to='hefs.halfproducten'),
        ),
    ]
