# Generated by Django 4.1.5 on 2024-06-06 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0060_remove_ingredienten_halfproduct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductenHalfproducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('halfproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hefs.halfproducten')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hefs.productinfo')),
            ],
            options={
                'unique_together': {('product', 'halfproduct')},
            },
        ),
    ]
