# Generated by Django 4.1.5 on 2024-06-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0062_productenhalfproducts_productcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='halfproducten',
            name='nodig_per_portie',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='halfproducteningredienten',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='ingredienten',
            name='nodig_per_portie',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='productenhalfproducts',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
    ]
