# Generated by Django 4.1.5 on 2024-06-11 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0063_alter_halfproducten_nodig_per_portie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredienten',
            name='nodig_per_portie',
        ),
    ]
