# Generated by Django 4.1.5 on 2024-07-01 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0064_remove_ingredienten_nodig_per_portie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leveranciers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(blank=True, max_length=250, null=True)),
                ('emailadres', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VerpakkingsSoort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=250)),
                ('afmeting_lengte_mm', models.IntegerField(default=0)),
                ('afmeting_breedte_mm', models.IntegerField(default=0)),
                ('afmeting_hoogte_mm', models.IntegerField(default=0)),
                ('stuks_per_krat', models.IntegerField(default=0)),
                ('kosten_per_eenheid', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='halfproducten',
            name='nodig_per_portie',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='afmeting_breedte_mm',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='afmeting_hoogte_mm',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='afmeting_lengte_mm',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='gang',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='inkoop',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='leverancier',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='verpakkingscombinatie',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='verpakkingsoort',
        ),
        migrations.AddField(
            model_name='productinfo',
            name='bereidingskosten',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='halfproducten',
            name='bereidingskosten_per_eenheid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Per KG/L/Stuk', max_digits=6),
        ),
        migrations.AlterField(
            model_name='halfproducten',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hefs.productinfo'),
        ),
        migrations.AlterField(
            model_name='halfproducteningredienten',
            name='halfproduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hefs.halfproducten'),
        ),
        migrations.AlterField(
            model_name='halfproducteningredienten',
            name='ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hefs.ingredienten'),
        ),
        migrations.AlterField(
            model_name='ingredienten',
            name='kosten_per_eenheid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Per KG/L/Stuk', max_digits=6),
        ),
        migrations.AlterField(
            model_name='neworders',
            name='verzendoptie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hefs.verzendopties'),
        ),
        migrations.AlterField(
            model_name='orderextra',
            name='productnaam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orderextra_productnaam', to='hefs.productinfo'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hefs.orders'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='verzendoptie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hefs.verzendopties'),
        ),
        migrations.AlterField(
            model_name='pickitems',
            name='pick_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hefs.pickorders'),
        ),
        migrations.AlterField(
            model_name='pickitems',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hefs.productinfo'),
        ),
        migrations.AlterField(
            model_name='pickorders',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hefs.orders'),
        ),
        migrations.AlterField(
            model_name='productenhalfproducts',
            name='halfproduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hefs.halfproducten'),
        ),
        migrations.AlterField(
            model_name='productenhalfproducts',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hefs.productinfo'),
        ),
        migrations.AlterField(
            model_name='productextra',
            name='extra_productnaam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productextra_extra_productnaam', to='hefs.productinfo'),
        ),
        migrations.AlterField(
            model_name='productextra',
            name='productnaam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productextra_productnaam', to='hefs.productinfo'),
        ),
        migrations.AlterField(
            model_name='verpakkingscombinaties',
            name='verpakkingsmogelijkheid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hefs.verpakkingsmogelijkheden'),
        ),
    ]
