# Generated by Django 4.1.5 on 2024-07-01 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0066_productinfo_bereidingskosten_per_eenheid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='halfproducten',
            name='bruikbare_hoeveelheid',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='halfproducten',
            name='leverancier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hefs.leveranciers'),
        ),
        migrations.AddField(
            model_name='halfproducten',
            name='verpakkingsoort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hefs.verpakkingssoort'),
        ),
    ]
