# Generated by Django 4.1.5 on 2024-07-01 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0068_ingredienten_btw_ingredienten_leverancier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlreadyProduced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('halfproduct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hefs.halfproducten')),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hefs.ingredienten')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hefs.productinfo')),
            ],
        ),
        migrations.CreateModel(
            name='ProductenIngredienten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hefs.ingredienten')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hefs.productinfo')),
            ],
            options={
                'unique_together': {('product', 'ingredient')},
            },
        ),
    ]
