# Generated by Django 4.1.5 on 2024-07-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0069_alreadyproduced_producteningredienten'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinfo',
            name='btw_percentage',
        ),
        migrations.AddField(
            model_name='halfproducten',
            name='btw',
            field=models.CharField(blank=True, choices=[('H', 'Hoog (21%)'), ('L', 'Laag (9%)'), ('0', 'Geen/0')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='btw',
            field=models.CharField(blank=True, choices=[('H', 'Hoog (21%)'), ('L', 'Laag (9%)'), ('0', 'Geen/0')], max_length=1, null=True),
        ),
    ]
