# Generated by Django 4.1.5 on 2024-07-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0070_remove_productinfo_btw_percentage_halfproducten_btw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producteningredienten',
            name='productcode',
            field=models.CharField(default=0, max_length=3),
        ),
    ]
