# Generated by Django 4.1.5 on 2024-10-23 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hefs', '0071_producteningredienten_productcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeverancierUserLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leverancier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hefs.leveranciers')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
