# Generated by Django 4.2.10 on 2024-11-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0074_route_alter_orderextra_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
