# Generated by Django 4.2.10 on 2024-11-25 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0075_orders_latitude_orders_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistanceMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_meters', models.IntegerField(null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distances_to', to='hefs.orders')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distances_from', to='hefs.orders')),
            ],
        ),
    ]
