# Generated by Django 4.2.10 on 2024-11-27 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0076_distancematrix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop', to='hefs.orders'),
        ),
    ]
