# Generated by Django 4.2.10 on 2024-11-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0077_alter_stop_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='google_maps_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
