# Generated by Django 4.2.10 on 2024-12-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0079_alter_route_google_maps_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='opmerkingen',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
    ]
