# Generated by Django 4.2.10 on 2024-12-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0080_orders_opmerkingen'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
