# Generated by Django 4.2.10 on 2024-12-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0081_route_departure_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='total_distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='total_travel_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
