# Generated by Django 4.2.10 on 2025-01-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0082_route_total_distance_route_total_travel_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminalLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.CharField(max_length=255, unique=True)),
                ('user_id', models.CharField(max_length=255)),
                ('shop_domain', models.URLField(max_length=255, unique=True)),
                ('location_id', models.CharField(blank=True, max_length=255, null=True)),
                ('staff_member_id', models.CharField(blank=True, max_length=255, null=True)),
                ('terminal_id', models.CharField(blank=True, max_length=255, null=True)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
