# Generated by Django 4.2.10 on 2025-01-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0083_terminallinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminallinks',
            name='shop_domain',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
