# Generated by Django 4.2.10 on 2025-01-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0084_alter_terminallinks_shop_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_url', models.CharField(max_length=255, unique=True)),
                ('tag_name', models.CharField(max_length=255, unique=True)),
                ('fee_product_id', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
