# Generated by Django 4.2.10 on 2025-01-14 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0085_feeproducts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feeproducts',
            old_name='fee_product_id',
            new_name='fee_variant_id',
        ),
    ]
