# Generated by Django 4.2.10 on 2025-01-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0086_rename_fee_product_id_feeproducts_fee_variant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeproducts',
            name='fee_variant_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='feeproducts',
            name='shop_url',
            field=models.CharField(max_length=255),
        ),
    ]
