# Generated by Django 4.2.10 on 2025-01-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0087_alter_feeproducts_fee_variant_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminallinks',
            name='shop_domain',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='terminallinks',
            name='shop_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='terminallinks',
            name='staff_member_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
