# Generated by Django 4.2.10 on 2025-01-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0090_syncinfo_geb_price_syncinfo_hob_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncinfo',
            name='geb_inventory_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='syncinfo',
            name='hob_inventory_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
