# Generated by Django 4.2.10 on 2025-03-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0091_syncinfo_geb_inventory_id_syncinfo_hob_inventory_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syncinfo',
            name='geb_id',
        ),
        migrations.RemoveField(
            model_name='syncinfo',
            name='geb_inventory_id',
        ),
        migrations.RemoveField(
            model_name='syncinfo',
            name='geb_price',
        ),
        migrations.RemoveField(
            model_name='syncinfo',
            name='geb_product_handle',
        ),
        migrations.RemoveField(
            model_name='syncinfo',
            name='geb_product_title',
        ),
        migrations.RemoveField(
            model_name='syncinfo',
            name='geb_variant_id',
        ),
        migrations.AddField(
            model_name='syncinfo',
            name='untappd_id',
            field=models.IntegerField(default=0),
        ),
    ]
