# Generated by Django 4.2.10 on 2025-03-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0092_remove_syncinfo_geb_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncinfo',
            name='hob_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
