# Generated by Django 4.2.10 on 2025-03-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0093_alter_syncinfo_hob_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncinfo',
            name='untappd_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
