# Generated by Django 4.2.10 on 2025-04-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0094_alter_syncinfo_untappd_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='HobOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=0)),
                ('shopifyID', models.BigIntegerField(default=0)),
                ('besteldatum', models.DateTimeField(blank=True, null=True)),
                ('verzendkosten', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('korting', models.IntegerField(blank=True, default=0, null=True)),
                ('orderprijs', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('voornaam', models.CharField(blank=True, max_length=250, null=True)),
                ('achternaam', models.CharField(blank=True, max_length=250, null=True)),
                ('tussenvoegsel', models.CharField(blank=True, max_length=250, null=True)),
                ('emailadres', models.CharField(blank=True, max_length=250, null=True)),
                ('telefoonnummer', models.CharField(blank=True, max_length=250, null=True)),
                ('straatnaam', models.CharField(blank=True, max_length=250, null=True)),
                ('huisnummer', models.CharField(blank=True, max_length=250, null=True)),
                ('postcode', models.CharField(blank=True, max_length=250, null=True)),
                ('plaats', models.CharField(blank=True, max_length=250, null=True)),
                ('land', models.CharField(blank=True, max_length=250, null=True)),
                ('opmerkingen', models.CharField(blank=True, max_length=2500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='syncinfo',
            name='deposit_money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='syncinfo',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
