# Generated by Django 4.2.10 on 2025-04-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0096_hoborders_sales_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoborders',
            name='shopifyID',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
