# Generated by Django 4.2.10 on 2025-04-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0098_hoborderproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoborderproducts',
            name='product_tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
