# Generated by Django 4.2.10 on 2025-04-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0099_hoborderproducts_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoborderproducts',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
