# Generated by Django 4.2.10 on 2025-04-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hefs', '0100_hoborderproducts_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoborderproducts',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price in euros (€)', max_digits=10),
        ),
    ]
